import type { Question } from "../model/types";

export const QUESTIONS: readonly Question[] = [
  {
    id: "perfect-weekend",
    kind: "choice-predict",
    category: "preferences",
    title: "Как выглядит идеальный совместный выходной?",
    description: "Не тот, который «надо бы», а тот, после которого не хочется понедельника.",
    options: [
      { id: "home", label: "Лежать дома и ничего не делать" },
      { id: "city", label: "Ресторан, бар, город" },
      { id: "nature", label: "Природа" },
      { id: "trip", label: "Спонтанно куда-нибудь уехать" },
      { id: "friends", label: "Провести время с друзьями" },
      { id: "parallel", label: "Каждый занимается своими делами" },
    ],
  },
  {
    id: "surprise-money",
    kind: "choice-predict",
    category: "values",
    title: "Внезапно дарят 100 000 ₽. Что происходит?",
    description: "Деньги уже на карте. Плана «как правильно» нет.",
    options: [
      { id: "save", label: "Отложить" },
      { id: "travel", label: "Потратить на путешествие" },
      { id: "wish", label: "Купить давно желанную вещь" },
      { id: "split", label: "Разделить: часть потратить, часть сохранить" },
      { id: "invest", label: "Инвестировать" },
      { id: "spent", label: "Потратить максимально тупо, но весело" },
    ],
  },
  {
    id: "after-conflict",
    kind: "choice-predict",
    category: "dynamics",
    title: "После небольшой ссоры ты скорее...",
    description: "Не драма на три дня. Обычная искра.",
    options: [
      { id: "first", label: "Первым пойду мириться" },
      { id: "pause", label: "Возьму паузу" },
      { id: "talk", label: "Попробую обсудить" },
      { id: "ignore", label: "Сделаю вид, что ничего не было" },
      { id: "joke", label: "Начну шутить" },
      { id: "wait", label: "Буду ждать первого шага" },
    ],
  },
  {
    id: "green-flag",
    kind: "choice-predict",
    category: "narrative",
    title: "Какой green flag здесь главный?",
    description: "Сначала угадай, какой свой флаг назовёт партнёр. Потом назови флаг, который видишь в партнёре.",
    predictPrompt: "Какой свой green flag, по-твоему, назовёт {partner}?",
    actualPrompt: "А какой green flag ты видишь в {partner}?",
    options: [
      { id: "kindness", label: "Доброта" },
      { id: "reliability", label: "Надёжность" },
      { id: "humor", label: "Чувство юмора" },
      { id: "care", label: "Забота" },
      { id: "ambition", label: "Амбициозность" },
      { id: "support", label: "Умение поддержать" },
      { id: "honesty", label: "Честность" },
      { id: "spontaneity", label: "Спонтанность" },
    ],
  },
  {
    id: "red-flag",
    kind: "choice-predict",
    category: "narrative",
    title: "Какой red flag здесь главный?",
    description:
      "Это игровой флаг по ответам теста, не диагноз. Сначала угадай, что назовут твоим. Потом назови, что видишь в партнёре.",
    predictPrompt: "Какой свой red flag, по-твоему, назовёт {partner}?",
    actualPrompt: "А какой red flag ты видишь в {partner}?",
    options: [
      { id: "stubborn", label: "Упрямство" },
      { id: "always-right", label: "«Я всегда прав»" },
      { id: "grudge", label: "Слишком долго обижаюсь" },
      { id: "lazy", label: "Лень" },
      { id: "impulse", label: "Импульсивность" },
      { id: "forgetful", label: "Забывчивость" },
      { id: "phone", label: "Слишком много телефона" },
      { id: "work", label: "Слишком много работаю" },
    ],
  },
  {
    id: "household-fight",
    kind: "choice-predict",
    category: "dynamics",
    title: "Из-за чего скорее случится первая большая бытовая ссора?",
    options: [
      { id: "money", label: "Деньги" },
      { id: "cleaning", label: "Уборка" },
      { id: "chores", label: "Кто что должен сделать" },
      { id: "space", label: "Личное пространство" },
      { id: "friends", label: "Друзья" },
      { id: "work", label: "Работа" },
      { id: "phone", label: "Телефон" },
      { id: "relatives", label: "Родственники" },
      { id: "vacation", label: "Отпуск" },
      { id: "listen", label: "«Ты опять меня не слушаешь»" },
    ],
  },
  {
    id: "who-leads",
    kind: "who-likely",
    category: "dynamics",
    title: "Кто скорее?",
    description: "Восемь коротких сцен. Я, партнёр или поровну.",
    scenarios: [
      { id: "writes-first", prompt: "Первый напишет после ссоры" },
      { id: "order-food", prompt: "Предложит заказать еду" },
      { id: "suggest-trip", prompt: "Предложит сорваться в поездку" },
      { id: "decides", prompt: "Примет решение" },
      { id: "changes-mind", prompt: "Передумает" },
      { id: "watches-money", prompt: "Проследит за деньгами" },
      { id: "forgets-date", prompt: "Забудет важную дату" },
      { id: "needs-talk", prompt: "Скажет «нам надо поговорить»" },
    ],
  },
  {
    id: "relocation",
    kind: "choice-predict",
    category: "values",
    title: "Работа мечты, но нужно переехать в другой город. Что происходит?",
    description: "Это не прогноз. Это то, как вы представляете такое решение.",
    predictPrompt: "Что сделает {partner}?",
    actualPrompt: "А что сделаешь ты?",
    options: [
      { id: "yes", label: "Согласится сразу" },
      { id: "rather-yes", label: "Скорее согласится" },
      { id: "no", label: "Откажется" },
      { id: "think", label: "Будет долго думать" },
      { id: "together", label: "Согласится только вместе" },
      { id: "depends", label: "Зависит от города и условий" },
    ],
  },
  {
    id: "earnings-future",
    kind: "choice-predict",
    category: "values",
    title: "Через 10 лет кто будет зарабатывать больше?",
    description:
      "Это не прогноз доходов. Это то, как вы представляете себя и партнёра. «Я» — тот, кто сейчас отвечает.",
    predictPrompt: "Как на этот вопрос ответит {partner}?",
    actualPrompt: "А как ответишь ты?",
    options: [
      { id: "self", label: "Я" },
      { id: "partner", label: "Партнёр" },
      { id: "equal", label: "Примерно одинаково" },
      { id: "unsure", label: "Сложно сказать" },
    ],
  },
  {
    id: "family-future",
    kind: "choice-predict",
    category: "preferences",
    title: "Какими вы будете как семья через 10 лет?",
    description: "Один вариант. Это ваша картина, не предсказание будущего.",
    options: [
      { id: "home", label: "Спокойно живём дома" },
      { id: "travel", label: "Постоянно путешествуем" },
      { id: "career", label: "Строим карьеру и бизнес" },
      { id: "kids", label: "Большая семья и дети" },
      { id: "active", label: "Живём очень активно" },
      { id: "abroad", label: "Переехали в другую страну" },
      { id: "house", label: "Свой дом" },
      { id: "unknown", label: "Пока вообще не знаем" },
    ],
  },
  {
    id: "future-values",
    kind: "multi",
    category: "values",
    title: "Выбери 3 вещи, которые важнее всего через 10 лет.",
    description: "Ровно три. Не больше.",
    maxSelections: 3,
    options: [
      { id: "money", label: "Деньги" },
      { id: "family", label: "Семья" },
      { id: "freedom", label: "Свобода" },
      { id: "career", label: "Карьера" },
      { id: "travel", label: "Путешествия" },
      { id: "stability", label: "Стабильность" },
      { id: "friends", label: "Друзья" },
      { id: "project", label: "Свой проект" },
      { id: "calm", label: "Спокойствие" },
    ],
  },
  {
    id: "never-forgive",
    kind: "choice-predict",
    category: "dynamics",
    title: "Что партнёр никогда не простит?",
    predictPrompt: "Что {partner} никогда не простит?",
    actualPrompt: "А что никогда не простишь ты?",
    options: [
      { id: "lie", label: "Врать" },
      { id: "ignore", label: "Игнорировать проблему" },
      { id: "control", label: "Контролировать" },
      { id: "break", label: "Нарушать договорённости" },
      { id: "phone", label: "Лезть в телефон" },
      { id: "flirt", label: "Флиртовать с другими" },
      { id: "space", label: "Лезть в личное пространство" },
      { id: "work", label: "Слишком много работать" },
    ],
  },
  {
    id: "typical-scene",
    kind: "choice",
    category: "dynamics",
    title: "Какая ваша самая типичная совместная ситуация?",
    options: [
      { id: "argue-food", label: "Спорим, куда пойти, и заказываем еду" },
      { id: "stay-home", label: "Собираемся выйти и остаёмся дома" },
      { id: "where", label: "Один предлагает сорваться, второй спрашивает «куда?»" },
      { id: "both-first", label: "Миримся так быстро, что оба считаем себя первыми" },
      { id: "trip-delivery", label: "Обсуждаем отпуск, пока кто-то открывает доставку" },
    ],
  },
  {
    id: "couple-sentence",
    kind: "text",
    category: "text",
    title: "Опишите вашу пару одним предложением.",
    description: "Напишите первое, что приходит в голову. Не пытайтесь красиво сформулировать.",
    placeholder: "Первое, что приходит в голову",
  },
];

export function getQuestion(id: string): Question | undefined {
  return QUESTIONS.find((question) => question.id === id);
}

export function optionLabel(question: Question, optionId: string): string {
  return question.options?.find((option) => option.id === optionId)?.label ?? optionId;
}
